spring:
  datasource:
    url: jdbc:mysql://test1.volia.com:3306/volia_test?useEncoding=true&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true
    username: volia_test
    password: 56WrtsXprBc
