spring:
  datasource:
    url: jdbc:mysql://mysql.prd.volia.com:3306/volia?useEncoding=true&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true
    username: volia
    password: volia
